In [1]:
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
from datasets import load_dataset
ds = load_dataset("valeriobasile/HatEval")

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'text', 'target', 'language', 'HS', 'TR', 'AG', '__index_level_0__'],
        num_rows: 13500
    })
    dev: Dataset({
        features: ['id', 'text', 'target', 'language', 'HS', 'TR', 'AG', '__index_level_0__'],
        num_rows: 1500
    })
    test: Dataset({
        features: ['id', 'text', 'target', 'language', 'HS', 'TR', 'AG', '__index_level_0__'],
        num_rows: 4570
    })
})

In [5]:
import pandas as pd

In [6]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [ ]:
train["level2"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
0,detests,d_0_01,d_0,La solución es desarrollar el pensamiento crít...,0,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
1,detests,d_0_02,d_0,Hay que enseñar que la magia no existe.,d_0_01,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
2,detests,d_0_03,d_0,Que todos los avances de la humanidad siempre ...,d_0_02,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
3,detests,d_0_04,d_0,Enseñar en las escuelas la historia de las rel...,d_0_03,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
4,detests,d_0_05,d_0,Desde las religiones de la edad de piedra hast...,d_0_04,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,stereohoax,s_4272,s_4272,Desde Canarias están pidiendo auxilio. Hay que...,0,s_4271,s_4271,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474
9902,stereohoax,s_4273,s_4273,marroquíes ya es mayor que el de la población...,0,s_4272,s_4271,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474
9903,stereohoax,s_4274,s_4274,Desde Canarias están pidiendo auxilio. Hay que...,0,0,s_4274,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474
9904,stereohoax,s_4275,s_4275,"Fuerteventura y Lanzarote, el número de marroq...",0,s_4274,s_4274,SP065,1,1,1,1,0.9526,1,1,0,1,0.7311
9905,stereohoax,s_4276,s_4276,"🇪🇸Canarias ya está ""ocupada"" por marroquíes y ...",0,0,s_4276,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474

In [11]:
train[train["comment_id"] == "d_0"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
0,detests,d_0_01,d_0,La solución es desarrollar el pensamiento crít...,0,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
1,detests,d_0_02,d_0,Hay que enseñar que la magia no existe.,d_0_01,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
2,detests,d_0_03,d_0,Que todos los avances de la humanidad siempre ...,d_0_02,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
3,detests,d_0_04,d_0,Enseñar en las escuelas la historia de las rel...,d_0_03,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
4,detests,d_0_05,d_0,Desde las religiones de la edad de piedra hast...,d_0_04,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
5,detests,d_0_06,d_0,Después de eso da igual lo que intenten adoctr...,d_0_05,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
6,detests,d_0_07,d_0,"Pero no es posible prohibir las religiones, po...",d_0_06,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474

In [12]:
train[train["comment_id"] == "d_1"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
7,detests,d_1_01,d_1,¿Manipulando?.,0,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
8,detests,d_1_02,d_1,"Un hecho real, que no me impide NO demonizar a...",d_1_01,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
9,detests,d_1_03,d_1,No se donde ves la manipulación.,d_1_02,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
10,detests,d_1_04,d_1,La realidad es obtusa con las generalizaciones,d_1_03,0,0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474

In [13]:
train[train["comment_id"] == "d_2"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
11,detests,d_2_01,d_2,Una procesión de semana santa potente hace que...,0,d_143,d_51,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
12,detests,d_2_02,d_2,"Lo mismo que la cabalgata de los reyes magos, ...",d_2_01,d_143,d_51,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
13,detests,d_2_03,d_2,Hay monjas de clausura y a algunas las obligan...,d_2_02,d_143,d_51,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474

In [10]:
train[train["level2"] == "d_143"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
11,detests,d_2_01,d_2,Una procesión de semana santa potente hace que...,0,d_143,d_51,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
12,detests,d_2_02,d_2,"Lo mismo que la cabalgata de los reyes magos, ...",d_2_01,d_143,d_51,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
13,detests,d_2_03,d_2,Hay monjas de clausura y a algunas las obligan...,d_2_02,d_143,d_51,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
4087,detests,d_1864_01,d_1864,El acogimiento de inmigración ilegal puede ser...,0,d_143,d_143,ABC20211105,1,1,1,1,0.9526,1,1,1,1,0.9526
4088,detests,d_1864_02,d_1864,La belleza del caballo ahora es humanitarismo,d_1864_01,d_143,d_143,ABC20211105,0,0,0,0,0.0474,0,0,0,0,0.0474

In [15]:
train[train["level3"] == "d_0"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
141,detests,d_50_01,d_50,Puedes enseñar lo que quieras que si no te qui...,0,d_0,d_0,20170819_CR,0,0,1,0,0.2689,0,0,1,0,0.2689
142,detests,d_50_02,d_50,Y éste es el caso.,d_50_01,d_0,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
168,detests,d_60_01,d_60,"No a los adultos, el que ya está adoctrinado e...",0,d_50,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
169,detests,d_60_02,d_60,Me refiero a los niños.,d_60_01,d_50,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
176,detests,d_62_01,d_62,La libertad de pensamiento sola no te garantiz...,0,d_152,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
177,detests,d_62_02,d_62,Eso solo no sirve absolutamente de nada sin se...,d_62_01,d_152,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
178,detests,d_62_03,d_62,Tu puedes tener la libertad de pensar que los ...,d_62_02,d_152,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
179,detests,d_62_04,d_62,Pero la libertad de pensamiento no te aleja de...,d_62_03,d_152,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
206,detests,d_71_01,d_71,Donde pongo “mutuamente exclusivas” quiero dec...,0,d_62,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
207,detests,d_71_02,d_71,Estoy empanao.,d_71_01,d_62,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
424,detests,d_149_01,d_149,Mientras no se olviden de enseñar el pastafari...,0,d_0,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
436,detests,d_152_01,d_152,La solución es inculcar la libertad de pensami...,0,d_0,d_0,20170819_CR,0,0,0,0,0.0474,0,0,0,0,0.0474
3817,detests,d_1721_01,d_1721,"A ver si lo he entendido. Un avión marroquí, l...",0,d_0,d_0,ABC20211105,0,0,0,0,0.0474,0,0,0,0,0.0474
3818,detests,d_1721_02,d_1721,Nadie ha controlado a los pasajeros y estos de...,d_1721_01,d_0,d_0,ABC20211105,0,0,0,0,0.0474,0,0,0,0,0.0474
3819,detests,d_1721_03,d_1721,"Definitivamente, en este pais no cabe un tonto...",d_1721_02,d_0,d_0,ABC20211105,0,0,0,0,0.0474,0,0,0,0,0.0474
3820,detests,d_1721_04,d_1721,"Da vergüenza ser español, nos toman por imbéci...",d_1721_03,d_0,d_0,ABC20211105,0,1,0,0,0.2689,0,1,0,0,0.2689
3821,detests,d_1721_05,d_1721,"No hay ningún país normal en el que pase esto,...",d_1721_04,d_0,d_0,ABC20211105,0,0,0,0,0.0474,0,0,0,0,0.0474
3822,detests,d_1721_06,d_1721,"Aquí no, porque en España los delincuentes, lo...",d_1721_05,d_0,d_0,ABC20211105,1,1,1,1,0.9526,1,1,0,1,0.7311
4038,detests,d_1832_01,d_1832,"Creo que se equivoca, .......... están en el g...",0,d_0,d_0,ABC20211105,0,0,0,0,0.0474,0,0,0,0,0.0474

In [17]:
train[train["source"] == "stereohoax"]

,source,id,comment_id,text,level1,level2,level3,level4,stereotype_a1,stereotype_a2,stereotype_a3,stereotype,stereotype_soft,implicit_a1,implicit_a2,implicit_a3,implicit,implicit_soft
5629,stereohoax,s_0,s_0,"El @user recuperará la ""sanidad universal"" y o...",0,0,s_0,SP003,1,1,1,1,0.9526,1,0,0,0,0.2689
5630,stereohoax,s_1,s_1,"El PSOE recuperará la ""sanidad universal"" y ob...",0,0,s_1,SP003,1,1,1,1,0.9526,1,0,0,0,0.2689
5631,stereohoax,s_2,s_2,Y los españoles dejaremos de pagar la sanidad ...,0,s_1,s_1,SP003,0,0,0,0,0.0474,0,0,0,0,0.0474
5632,stereohoax,s_3,s_3,Una cosa os voy a decir: con el listón que se ...,0,0,s_3,SP003,0,0,0,0,0.0474,0,0,0,0,0.0474
5633,stereohoax,s_4,s_4,De una persona que se manifiesta a favor de su...,0,s_3,s_3,SP003,0,0,0,0,0.0474,0,0,0,0,0.0474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,stereohoax,s_4272,s_4272,Desde Canarias están pidiendo auxilio. Hay que...,0,s_4271,s_4271,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474
9902,stereohoax,s_4273,s_4273,marroquíes ya es mayor que el de la población...,0,s_4272,s_4271,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474
9903,stereohoax,s_4274,s_4274,Desde Canarias están pidiendo auxilio. Hay que...,0,0,s_4274,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474
9904,stereohoax,s_4275,s_4275,"Fuerteventura y Lanzarote, el número de marroq...",0,s_4274,s_4274,SP065,1,1,1,1,0.9526,1,1,0,1,0.7311
9905,stereohoax,s_4276,s_4276,"🇪🇸Canarias ya está ""ocupada"" por marroquíes y ...",0,0,s_4276,SP065,1,1,1,1,0.9526,0,0,0,0,0.0474

In [18]:
train[train["source"] == "stereohoax"]["level1"].unique()

array(['0'], dtype=object)

In [21]:
"""
DETESTS-Dis EDA
===============
Run: pip install datasets pandas matplotlib seaborn scipy
     python detests_eda.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from collections import Counter
import warnings
warnings.filterwarnings("ignore")

# ── load ──────────────────────────────────────────────────────────────────────
try:
    from datasets import load_dataset
    ds = load_dataset("CLiC-UB/DETESTS-Dis", split="train")
    df = ds.to_pandas()
    print(f"Loaded {len(df):,} rows from HuggingFace")
except Exception as e:
    print(f"Could not load from HuggingFace: {e}")
    raise

# ── style ─────────────────────────────────────────────────────────────────────
PALETTE = {
    "detests":   "#4A7FC1",
    "stereohoax": "#D85A30",
    "yes":  "#D85A30",
    "no":   "#4A7FC1",
    "agree": "#3B6D11",
    "disagree": "#BA7517",
}
sns.set_theme(style="whitegrid", font_scale=1.05)
plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor":   "white",
    "axes.edgecolor":   "#cccccc",
    "axes.spines.top":  False,
    "axes.spines.right": False,
})

SOFT_BINS = [0.0474, 0.2689, 0.7311, 0.9526]
BIN_LABELS = ["0/3\n(0.05)", "1/3\n(0.27)", "2/3\n(0.73)", "3/3\n(0.95)"]


# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 1 — Label distributions
# ═══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(2, 3, figsize=(16, 9))
fig.suptitle("Figure 1 — Label distributions", fontsize=15, fontweight="bold", y=0.98)

sources = df["source"].unique()
src_colors = [PALETTE["detests"], PALETTE["stereohoax"]]

# 1a — stereotype hard label by source
ax = axes[0, 0]
ct = df.groupby(["source", "stereotype"]).size().unstack(fill_value=0)
ct.plot(kind="bar", ax=ax, color=[PALETTE["no"], PALETTE["yes"]], edgecolor="white", width=0.6)
ax.set_title("Stereotype label by source")
ax.set_xlabel("")
ax.set_ylabel("Sentence count")
ax.set_xticklabels(ct.index, rotation=0)
ax.legend(["No stereotype (0)", "Stereotype (1)"], frameon=False)
for p in ax.patches:
    ax.annotate(f"{int(p.get_height()):,}", (p.get_x() + p.get_width()/2, p.get_height()),
                ha="center", va="bottom", fontsize=9)

# 1b — implicit hard label by source
ax = axes[0, 1]
ct2 = df[df["stereotype"] == 1].groupby(["source", "implicit"]).size().unstack(fill_value=0)
ct2.plot(kind="bar", ax=ax, color=[PALETTE["no"], PALETTE["yes"]], edgecolor="white", width=0.6)
ax.set_title("Implicit vs explicit (stereotype=1 only)")
ax.set_xlabel("")
ax.set_ylabel("Sentence count")
ax.set_xticklabels(ct2.index, rotation=0)
ax.legend(["Explicit (0)", "Implicit (1)"], frameon=False)

# 1c — stereotype × implicit joint heatmap
ax = axes[0, 2]
joint = df.groupby(["stereotype", "implicit"]).size().unstack(fill_value=0)
sns.heatmap(joint, annot=True, fmt="d", cmap="Blues", ax=ax,
            linewidths=0.5, cbar_kws={"shrink": 0.7})
ax.set_title("Stereotype × implicit joint distribution")
ax.set_xlabel("Implicit")
ax.set_ylabel("Stereotype")

# 1d — soft label distribution (stereotype_soft)
ax = axes[1, 0]
soft_counts = df["stereotype_soft"].round(4).value_counts().reindex(
    [round(b, 4) for b in SOFT_BINS], fill_value=0
)
bars = ax.bar(BIN_LABELS, soft_counts.values,
              color=[PALETTE["no"], "#8aabda", "#e09070", PALETTE["yes"]],
              edgecolor="white", width=0.6)
ax.set_title("Stereotype soft-label distribution")
ax.set_xlabel("Annotator votes (soft value)")
ax.set_ylabel("Sentence count")
for b, v in zip(bars, soft_counts.values):
    ax.text(b.get_x() + b.get_width()/2, v + 30, f"{v:,}",
            ha="center", va="bottom", fontsize=9)

# 1e — soft label distribution (implicit_soft)
ax = axes[1, 1]
soft_counts2 = df[df["stereotype"] == 1]["implicit_soft"].round(4).value_counts().reindex(
    [round(b, 4) for b in SOFT_BINS], fill_value=0
)
bars2 = ax.bar(BIN_LABELS, soft_counts2.values,
               color=[PALETTE["no"], "#8aabda", "#e09070", PALETTE["yes"]],
               edgecolor="white", width=0.6)
ax.set_title("Implicit soft-label distribution\n(stereotype=1 only)")
ax.set_xlabel("Annotator votes (soft value)")
ax.set_ylabel("Sentence count")


plt.tight_layout()
plt.savefig("fig1_label_distributions.png", dpi=150, bbox_inches="tight")
print("Saved fig1_label_distributions.png")
plt.close()





# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 3 — Text & conversational properties
# ═══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("Figure 3 — Text and conversational properties", fontsize=15, fontweight="bold")

df["token_count"] = df["text"].str.split().str.len()

# 3a — sentence length distribution by stereotype label
ax = axes[0]
for label, color in [(0, PALETTE["no"]), (1, PALETTE["yes"])]:
    subset = df[df["stereotype"] == label]["token_count"]
    ax.hist(subset, bins=40, alpha=0.6, color=color, label=f"Stereotype={label}", density=True)
ax.set_title("Sentence length by stereotype label")
ax.set_xlabel("Token count")
ax.set_ylabel("Density")
ax.legend(frameon=False)
ax.set_xlim(0, 120)

# 3b — sentence length by soft label bin
ax = axes[1]
def assign_bin(v):
    v = round(v, 4)
    if v <= 0.05:   return "0/3"
    elif v <= 0.27: return "1/3"
    elif v <= 0.74: return "2/3"
    else:           return "3/3"

df["soft_bin"] = df["stereotype_soft"].apply(assign_bin)
order = ["0/3","1/3","2/3","3/3"]
bin_colors = [PALETTE["no"], "#8aabda", "#e09070", PALETTE["yes"]]
data_by_bin = [df[df["soft_bin"] == b]["token_count"].values for b in order]
bp = ax.boxplot(data_by_bin, labels=order, patch_artist=True, medianprops={"color":"white","linewidth":2})
for patch, color in zip(bp["boxes"], bin_colors):
    patch.set_facecolor(color)
ax.set_title("Sentence length by soft label bin")
ax.set_xlabel("Annotator agreement (votes)")
ax.set_ylabel("Token count")
ax.set_ylim(0, 100)

# 3c — stereotype rate by position within comment (DETESTS only)
ax = axes[2]
det = df[df["source"] == "detests"].copy()
det["position"] = det.groupby("comment_id").cumcount() + 1
pos_rate = det[det["position"] <= 10].groupby("position")["stereotype"].mean() * 100
ax.plot(pos_rate.index, pos_rate.values, marker="o", color=PALETTE["detests"], linewidth=2)
ax.fill_between(pos_rate.index, pos_rate.values, alpha=0.15, color=PALETTE["detests"])
ax.set_title("Stereotype rate by sentence position\nin comment (DETESTS, positions 1–10)")
ax.set_xlabel("Sentence position in comment")
ax.set_ylabel("% with stereotype")
ax.set_xticks(pos_rate.index)

plt.tight_layout()
plt.savefig("fig3_text_properties.png", dpi=150, bbox_inches="tight")
print("Saved fig3_text_properties.png")
plt.close()

print("\nAll figures saved. Open fig1_*.png, fig2_*.png, fig3_*.png to view.")

Loaded 9,906 rows from HuggingFace
Saved fig1_label_distributions.png
Saved fig3_text_properties.png

All figures saved. Open fig1_*.png, fig2_*.png, fig3_*.png to view.

In [23]:
articles = pd.read_csv("level4.csv")

In [24]:
articles

               id                                               text
0           SP003  Costear la sanidad de los inmigrantes ilegales...
1           SP013  si eres un currante español pagas 1.500 euros ...
2           SP017  “un joven canario agredido por un inmigrante i...
3           SP036  España es el único país europeo que firmará el...
4           SP043  Estos son los Menas (menores no acompañados) a...
5           SP048  El Ministerio del Interior en colaboración con...
6           SP054  El foco de la calle Nicolás Salmerón que es la...
7           SP064  El Diputado de Podemos Serigne Mbayé pide acab...
8           SP067  "profesionales de la educación son amordazados...
9           SP070  los bares cierran a la una y se limita el afor...
10          SP005  La Cruz roja atiende solo a inmigrantes en Alg...
11          SP052  "69% de las agresiones cometidas en manada" la...
12          SP055  la Policia acaba de detener a CUATRO inmigrant...
13          SP065  Canarias ya está "ocupada" por marroquíes y ma...
14          SP068  cada año que pasa, los extranjeros copan más y...
15          SP008  España se va a hacer cargo, a cambio de una mi...
16          SP009  Aquí van a ser alojados 100 emigrantes ilegale...
17          SP010  los embarcaderos de Nuadibú, al Norte de la Re...
18          SP014  cuando llegan las personas migrantes a Canaria...
19          SP015  en “Fuerteventura y Lanzarote el número de mor...
20          SP020        los inmigrantes "han robado en una iglesia"
21          SP023  "Me he enterado que los menas ganan 4.700 eura...
22          SP027  Un mena pega una paliza a un gay en Pontevedra...
23          SP031  Rumanos, ecuatorianos y marroquíes se comen 7 ...
24          SP040  los musulmanes demandarán a España ante Estras...
25          SP047  Podemos creará en España las nuevas playas par...
26          SP049  El Gobierno de Pedro Sánchez ha aprobado este ...
27          SP057  Cien mil inmigrantes cobran pensiones contribu...
28    20170819_CR  Los investigadores sitúan al nuevo imán de Rip...
29    20190716_CR                    Un 'cortacabezas' en la patera.
30    20200708_MI  Unidas Podemos propone regularizar a los 600.0...
31   20200715b_CR  El TSJ de Extremadura confirma la expulsión de...
32    20200725_CR  Dos menores estrangulan a una mujer para robar...
33    20200831_CR  Al menos cuatro detenidos por abusar de una me...
34    ABC20210520  Luna, la joven de Cruz Roja que conmovió al co...
35    ABC20211105  Inmigrantes ilegales paralizan el aeropuerto d...
36     AD20200719  Lo que nadie cuenta sobre lo que ha pasado con...
37     EC20210829  La otra crisis con la que lidia Ceuta: un terc...
38     EM20210519  La trabajadora de Cruz Roja que consoló a un i...
39     EM20211106  Una "patera aérea", una nueva e insólita maner...
40    20230409_DS  Acusados de agredir sexualmente a una joven en...
41    20231123_DV  Vivir en la calle da miedo. Te roban, te agred...
42   20231004_20M  Llegada masiva de migrantes a El Hierro: la is...
43    20231117_ED  De Dinamarca a Finlandia: el fin de la cultura...
44    20230731_EC  Expulsan a Marruecos a un joven detenido hasta...
45  20230731-B_EC  Expulsan a Marruecos a un joven detenido hasta...